import type { Metadata } from "next";
import { Nunito, Playfair_Display } from 'next/font/google';
import "./ui/globals.css";

const nunito = Nunito({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});
const playfairDisplay = Playfair_Display({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-playfair-display',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${nunito.variable}`}>
      <body>{children}</body>
    </html>
  );
}
